# Generated by Django 4.1.7 on 2023-06-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
