# Generated by Django 4.2 on 2023-05-02 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_author_is_active_book_is_active_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1683009637/default_klejaw.png', max_length=255, verbose_name='image'),
        ),
    ]
