# Generated by Django 4.2 on 2023-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
